### ISSUE TITLE
Private Subnets when connecting to Secure Hub

### ISSUE THREAD

**Issue by SleepyWheezal** [MitchellGulledge/Meraki-vWAN#31] opened 2021-05-12 14:35 UTC
We have ran into a couple of issue when attaching to a Secure Hub

**Scenario One**

We have a secure hub configured as per the following link
https://docs.microsoft.com/en-us/azure/virtual-wan/scenario-route-between-vnets-firewall

From my understanding the function pulls the vnet address by looking for effective routes to vnets in the default route table.
  
Due to no Azure API existing for connected networks to the hub, pull connected VNets via effective routes
    effective_routes_endpoint = _get_microsoft_network_base_url(_AZURE_MGMT_URL, AzureConfig.subscription_id, resource_group)\
                        + f"/virtualHubs/{virtual_wan_hub}/effectiveRoutes?api-version=2020-05-01"

However all our vnet traffic goes via a firewall, so we don't have any effective routes to vnets. Hence this comes back empty and we end up with the placeholder entry in the Private Subnet field.

**Scenario Two**

In addition we temporarily have a additional non-meraki VPN to a datacentre, this is routable through the Secure Hub, however we need a mechanism of catching this in the private subnet field.

Could the function be amended to add the option to manually define the private subnet field, so it is a little more flexible.

Thanks in advance.

**Comment by MitchellGulledge** [comment] 2021-05-12 19:05
Thanks for the great description of the problem :) quick question, for the private subnets field and sending traffic to the secure hub are you using the secure hub as the internet gateway as well (as in a default route is being generated from the Azure Firewall) or that you have a bunch of VNETs using the SecureHub as their default gateway and we need a way to pull the FW VNET routes in addition to a default route via the API? (I hope that made sense apologies if not)

**Comment by SleepyWheezal** [comment] 2021-05-12 19:41
Hi, thanks for getting back so quickly. Sorry not sure it what you mean, but it is the end of a long day. The secure hub is the internet break gateway for the VNETs and essentially any traffic from a site to a VNET will traverse the firewall. So pretty sure by your description it is a default route generated by the Firewall. Basically we have defined a static route in the hub that directs all traffic in the VNET IP ranges into the firewall. The other issue is we have a VPN to an on-prem Datacentre, that doesn't have Meraki, it's another site,  however not sure how we can capture the IP range..

**Comment by SleepyWheezal** [comment] 2021-05-17 16:16
Hi Mitchell, is this something you could help with? Just working out whether we should hold on or create our own branch. Thanks.

**Comment by MitchellGulledge** [comment] 2021-05-17 23:31
Hey, apologies for the delay. How soon would this need to be implemented? And how many sites? We might be able to get another branch off main with the fix and I could have a button on that branch deploy from that code. But it would take some time (maybe a week or two) due to competing priorities. But also that doesnt mean I dont break other parts of the script and delay another week :( But your description of the problem made perfect sense. It might be easier to add some logic to append custom subnets from the effective routes. But to pull from the Azure FW routes will be the more difficult part to put in the code. (Azure has all the API endpoints we need to do this, its just working that into the logic) Would another solution be fore you to just fill in the private subnets field containing the Azure FW prefixes in the interim? (This might be quicker to fix)

**Comment by SleepyWheezal** [comment] 2021-05-18 09:13
Hi thank you for getting back we appreciate your time. Looking at around twenty sites. I've looked at adding in application setting just to manually catch the private subnets, seem fine for an interim solution. We are looking to start moving sites into production in the couple of  weeks.

**Comment by MitchellGulledge** [comment] 2021-05-20 17:53
Awesome, I could likely start kicking off some code next week so we can hopefully have a branch for you to test. Just so I understand, I will create a field under where you enter your api key vwan name etc and have a field called private subnets and you can paste a list of prefixes and the code will replace the placeholder field for 1.1.1.1/32. Would that work?

**Comment by SleepyWheezal** [comment] 2021-05-20 18:29
Yes, that will work. It will give us a little more flexibility with the private subsets. Thanks for picking it up.

________________________________

**Comment by MitchellGulledge** [comment] 2021-05-28 01:21
Does azure_custom_prefixes make sense for the naming of the field?

**Comment by MitchellGulledge** [comment] 2021-05-28 01:29
`

    #api_key = os.environ['meraki_api_key'].lower()
    #org_name = os.environ['meraki_org_name']
    #use_maintenance_window = os.environ['use_maintenance_window']
    #maintenance_time_in_utc = int(os.environ['maintenance_time_in_utc'])
    #tag_prefix = 'vwan-'
    #primary_tag_regex = f"(?i)^{tag_prefix}([a-zA-Z0-9_-]+)-[0-9]+$"
    #secondary_tag_regex = f"(?i)^{tag_prefix}([a-zA-Z0-9_-]+)-[0-9]+-sec$"
    #org_id = None
    # authenticating to the Meraki SDK
    #sdk_auth = meraki.DashboardAPI(api_key)

    # custom prefixes can be defined by the customer in order to account for 
    # subnets outside the Azure effective routes table
    custom_prefixes = os.environ['azure_custom_prefixes']




'''
The goal is to have the new_meraki_vpns be new_meraki_vpns + custom_prefixes

            # Update Meraki VPN config
            update_meraki_vpn = MerakiConfig.sdk_auth.appliance.updateOrganizationApplianceVpnThirdPartyVPNPeers(
                MerakiConfig.org_id, new_meraki_vpns
                )

'''

'''
The new logic will have the following conditional statement to account for the custom prefixes

            # if statement to check whether the length of the custom_prefixes list is greater than 0
            if len(custom_prefixes) > 0:
                new_meraki_vpns = new_meraki_vpns + custom_prefixes

            # Update Meraki VPN config
            update_meraki_vpn = MerakiConfig.sdk_auth.appliance.updateOrganizationApplianceVpnThirdPartyVPNPeers(
                MerakiConfig.org_id, new_meraki_vpns
                )

'''`

If that makes sense I can work on testing the code as this seems straightforward enough :)

**Comment by SleepyWheezal** [comment] 2021-05-28 15:06
I'd be tempted to stick with Private Subnets so it matches the terminology in the Meraki Portal. I don't know enough about the Meraki APIs, I'll have to assume the rest is fine. I'm guess this is an array, so we can send assign multiple subnets?

**Comment by MitchellGulledge** [comment] 2021-05-28 17:05
that makes more sense, I will work on adding and testing today/over the weekend so you should hopefully have something you can deploy with no issues next week :)

**Comment by MitchellGulledge** [comment] 2021-05-28 17:18
also the entry will be a list of comma separated IPs, so like ['1.1.1.1/30', '2.2.2.2/30', '3.3.3.3/30'] Essentially a list of strings in python. Going to had some error handling in there potentially to account for typos or missed quotes.

**Comment by SleepyWheezal** [comment] 2021-06-07 08:04
Hi Mitchell, do you have an idea when this might be completed?

**Comment by MitchellGulledge** [comment] 2021-06-09 14:42
Apologies for delay had other priorities/escalations backlog this. Please allow me a few more days and apologies for the delay.

**Comment by MitchellGulledge** [comment] 2021-06-11 05:17
Quick Update, my tests all seem to be passing so will try to get this on a public branch either tomorrow or Monday :)

**Comment by SleepyWheezal** [comment] 2021-06-11 13:48
Brilliant, thanks

**Comment by MitchellGulledge** [comment] 2021-06-13 01:33
Whenever you are ready you can try the new deployment out with this button in the page: https://github.com/MitchellGulledge/Meraki-vWAN/tree/v1API for the meraki_private_subnets field just provide a list of IPs with no quotes or brackets or anything. So for example: 1.1.1.1/30, 2.2.2.2/32

It is working fine for me now so hopefully this finds you well :)

**Comment by SleepyWheezal** [comment] 2021-06-14 11:00
Thank you, I have deployed the app. However, we have an unrelated outage, so can't test it yet. I'll let you know as soon as we can.

**Comment by MitchellGulledge** [comment] 2021-06-21 22:38
Hey, just wanted to circle back and see if you wanted to redeploy the app again? I made a few commits to make this more bulletproof and even updated the Meraki documentation to include this new functionality.

**Comment by SleepyWheezal** [comment] 2021-06-22 10:00
Hi Mitchell

Thanks,  I’ve redeployed with the latest version. It works, but I have a couple of comments.


  *   As we don’t have any appropriate effective routes the script picks up the placeholder (1.1.1.1) entry along with private subnets we enter. It doesn’t affect operations, but would be nice to tidy up.
  *   I have an additional issue, which I’m not sure if it is just this version of the code affected, but when setting up a new VPN, the Azure Gateway and Connectivity Status Fails. If I then go into the new VPN settings in on the Gateway and save, this is without changing any settings, the gateway config saves and everything connects as expected. I can’t see any errors in the function.

***@***.***D76755.D12BAAE0]


  *   I also get the 500 server error when attempting to invoke the function, as mentioned elsewhere.

Regards

Peter

**Comment by MitchellGulledge** [comment] 2021-06-22 15:32
So when you try to manually trigger the function vs waiting for the timer you see the 500 error? And also just so I understand you are still seeing that annoying placeholder for effective routes of 1.1.1.1/32 which doesnt affect anything but looks odd. Other than that the function appears to be working as expected?

**Comment by SleepyWheezal** [comment] 2021-06-22 15:37
Yes, when I trigger the function I see the 500 error.  I can’t see any problems when it runs off the timer.

**Comment by MitchellGulledge** [comment] 2021-06-22 16:44
The manual trigger makes sense, there is no path the function has when executing the manual trigger to trigger the main function. (I could be wrong, but I do not think the manual trigger is expected to work with the code as it is today) Regarding the 1.1.1.1/32 subnet I can fix that with some additional logic but you would have to redeploy the app again once I merge the fix if that is okay with you?

**Comment by SleepyWheezal** [comment] 2021-06-24 08:47
Hi

That’s fine, let me know when you have made the merges.

Peter

**Comment by SleepyWheezal** [comment] 2021-06-24 10:04
Sorry, looks like we may have found an issue, we have brought on board a second site and it looks like it doesn’t pick up the private subnets for both sites. One site pickups the private subnets as expected, one site only picks up the placeholder. Behaviour was bit glitchy, essentially


  *   Added second site and script built it correctly.
  *   During the overnight maintenance window firsts site lost the private subnets. Looking at the Meraki logs this didn’t happen immediately, but towards the end of the maintenance window the config pushed out changed.
  *   Found the issue this morning, manually edited the Meraki config.

I’ll leave the script running to see if this happens again tonight.

Thanks

Peter

From: Pete ***@***.***>
Sent: 24 June 2021 09:47
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [MitchellGulledge/Meraki-vWAN] Private Subnets when connecting to Secure Hub (#31)

Hi

That’s fine, let me know when you have made the merges.

Peter

**Comment by MitchellGulledge** [comment] 2021-06-24 17:40
That is super strange, please let me know the results and I will hold off for now making any changes until we confirm this wasnt one off. (I was pushing changes yesterday and this could have been timing with when I pushed some changes so will standby)

**Comment by SleepyWheezal** [comment] 2021-06-28 09:33
Unfortunately it seems to be consistent. We have two sites and during the maintenance window one site loses its private subnets. I've attached the screen shot of the log from the Meraki side, where we can see it pushed out from the script. Let me know if there is anything else I can do to help troubleshoot.

[cid:ee1d4cdf-6f6e-4ced-a577-da2655a2482c]


________________________________

**Comment by MitchellGulledge** [comment] 2021-06-28 16:36
I am unfortunately not able to see the screenshot, do you mind sharing your meraki S/N and I can take a look at the logs while I recreate here as well?

**Comment by SleepyWheezal** [comment] 2021-06-29 08:00
We have removed the site that was having the issue, and it is now affecting the next sit on the list. It is also happening every time we perform an apply now. For info the private subnets that should be passed over are 10.12.0.0/16, 1.106.106.0/24, I'm assuming the formatting is correct.
The device serial is Q2KY-R6CS-B2GG, let me know if you need anything else. Thanks




________________________________

**Comment by MitchellGulledge** [comment] 2021-06-29 16:58
Alright will get to the bottom of this. I have recreated this and configured the same custom subnets. I think this is going to be where I placed the logic in the loop. Will update as soon as I find more out. (Hopefully very soon)

**Comment by MitchellGulledge** [comment] 2021-06-29 17:38
Think I found the issue! So in the v1API2 branch created for you the azuredeploy.json file here: https://github.com/MitchellGulledge/Meraki-vWAN/blob/v1API2/azuredeploy.json is pulling this:
`    "variables": {
        "hostingPlanName": "[parameters('function_app_name')]",
        "storageAccountName": "[concat('storage', uniquestring(resourceGroup().id))]",
        "functionPackage": "https://github.com/MitchellGulledge/Meraki-vWAN/raw/v1API/MerakiFunction.zip"
    },`
 going to update this and retest

**Comment by MitchellGulledge** [comment] 2021-06-29 18:01
<img width="1199" alt="Screen Shot 2021-06-29 at 11 01 23 AM" src="https://user-images.githubusercontent.com/61255163/123845713-5b7ee100-d8c9-11eb-85d2-4d0bb2532746.png">
Looks like it worked, will continue to monitor/test but it looks good!

**Comment by MitchellGulledge** [comment] 2021-06-30 16:57
want to redeploy the fun ction app and see if it works for you? I am 24 hours without any app errors.

**Comment by SleepyWheezal** [comment] 2021-07-05 09:08
Hi, thank you for your work on this. I will update the function later today.

**Comment by SleepyWheezal** [comment] 2021-07-06 07:47
Hi, I’ve deployed the v1API2 branch, I’m not sure the deployment button is pointing to the correct azuredeploy file as it didn’t include the private subnet option. However I deployed by using the file in a custom template and it seems to be working.  I will give it a few days and let you know.

**Comment by MitchellGulledge** [comment] 2021-07-06 21:30
strange, can you try deploying from the documentation: https://documentation.meraki.com/MX/Deployment_Guides/Cisco_Meraki_MX_Branch_to_Azure_Virtual_WAN_Deployment_Guide or is that what you did?

**Comment by MitchellGulledge** [comment] 2021-07-08 04:37
I can confirm the button I had in documentation is the correct one and the github readme should just be updated for that branch. It still points to stale branch.. apologies

**Comment by SleepyWheezal** [comment] 2021-07-22 15:59
Hi Mitchell

Sorry it has taken a while to get back, I had a few challenges with A/L and work. However I’ve successfully redeployed the function using the link in the doc and I haven’t seen a repeat of the issue with the private subnets. So it can be marked as resolved.

However I do have another issue, don’t know if you can shed any light on it. We have three sites setup so far and for all but the first site we get an error in the function.


2021-07-22 15:50:49.818
Could not create Virtual WAN connection.
Error
2021-07-22 15:50:49.820
Response: { "error": { "code": "AnotherOperationInProgress", "message": "Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/6acff128-1185-4964-bf3f-62488279fb8f/providers/Microsoft.Network/locations/uksouth/operations/13ff3b56-f49a-4ecf-919a-2f872f2e3e20?api-version=2020-05-01.", "details": [] } }
Error
2021-07-22 15:50:49.821
Virtual WAN Connection for DebdenGrange could not be created, skipping to next network.
Error


However despite this the site does configure correctly, the knock on being it doesn’t clear the vwan-apply-now tag.

Thanks

Peter

**Comment by MitchellGulledge** [comment] 2021-07-22 19:44
I am going to close this issue, and open a new issue with the vwan-apply-now tag not being cleared. Thanks for your patience

**Closed as completed by MitchellGulledge** 2021-07-22 19:44 UTC
